### ISSUE TITLE
Add multiple paths to KiCAD templates and dropdown in KiCad window

### ISSUE THREAD

**Issue by rogers-jp** [sparkmicro/Ki-nTree#68]
Thanks for a really great tool!  I've managed to get this working but not without a couple of minor hiccups I thought it might be helpful to share.  I've done a system-wide install on macOS Big Sur 11.6.  The processor is an M1, which *may* be important to this issue because I've found there's very little support for installing certain common python packages like numpy and scipy on M1 machines.  But I don't have any concrete reason why it would cause the issues I've had...

Anyway, to the issues I found: 
1. I had to use `pip3 install -U kintree` rather than `pip install -U kintree`.  That may just be because of the way I have python and pip installed on my machine.  Probably not your problem but I mention it for completeness.
2. tkinter was not installed so I had to brew install that.  From what I gather that should have been included in the python3.9 installation but for some reason was not.  Again, probably not your problem.
3. When I first ran the `kintree` command, it told me it couldn't find the `'images/logo.png'` file called in line 913 of `kintree_gui.py`.  I went looking to see where this file might be but I couldn't see a directory called images or a file called logo.png anywhere nearby.  I figured it was probably just decorative so I just commented it out.  The GUI then launched nicely.  
4. I put in my newly acquired Mouser and DigiKey API keys and successfully searched for some parts on each service.  However, they wouldn't add to the KiCAD library I had specified.  The error in Terminal was that it couldn't find the KiCAD templates files.  I had seen these back in the homebrew directory in `/opt/homebrew/lib/python3.9/site-packages/kintree/kicad/templates/` so I found the kicad.yaml file in my User folder and put in the fully resolved path.  It now successfully adds these parts to my KiCAD library and I'm very happy with this!

I don't know if I'm doing anything wrong but at the moment if there is a unique footprint associated with the part, I presume I have to download that file separately and tell kintree where it is so they can be associated.  I've used Library Loader on Windows before and it fetches the footprint and 3D model (if they're available) alongside the symbol.  Am I missing something in kintree?  Or would this information not be quite so straightforward for kintree to obtain alongside the rest of the product information?

Thanks for your time!

**Comment by eeintech** [comment]
Hello @rogers-jp

Thanks for the really detailed feedback :+1: 

1. Looks like Apple decided to stick to Python 2.7, sorry for that... most cases the `python` command loads newer version of pythons (eg. 3.6+), I'm glad you figured out the quick solution in your case!
2. Interesting... didn't think Python would ditch Tkinter, or could it be a brew driven decision? Not super familiar with the matter :confused: 
3. Seems like I introduced a bug in the last version #69 and that it is not isolated to Windows then... sorry for that and I shall fix it soon!
4. That's right Ki-nTree and template files should be loaded inside the `site-packages` folder, it is strange that you couldn't select the KiCad template files using the GUI instead of writing the `kicad.yaml` file directly... I am surprised but I'll have to double check.

That's correct, footprints can be either created or downloaded from SnapEDA / UltraLibrarian then moved to your footprint library. If you refresh the list of footprints using the "Confirm" button of the KiCad setup window, you should see the footprint appear in the list then you can select it.
I did not know about Library Loader, [is this it?](https://www.samacsys.com/library-loader/)

Ki-nTree cannot currently fetch directly symbols, footprints and 3D models from SnapEDA, I was told this kind of access is reserved for their [KiCad plugin](https://www.snapeda.com/plugins/). I would love to be able to do bypass the need for manual entry for symbol template, footprint and 3D model (and I've tried to tell them to let me do that) but unfortunately Ki-nTree is limited to the current features for the time being, sorry!

**Comment by rogers-jp** [comment]
Hi @eeintech , thanks for your reply.  Regarding point 4, I saw after I submitted my issue that the GUI has a dialog box for the templates folder in the KiCad settings menu.  The default value in there was, I think, a relative path.  It was short, something like `kicad/templates/`.  As I said, I actually edited the yaml file directly but had to put in the fully resolved path to the directory in order for it to work...from your installation instructions, I don't think I was expecting to have to do that but perhaps I was wrong...

Yes, that's the Library Loader I used.  It's pretty powerful once you get it working.  As soon as you download a component entry from componentsearchengine.com, Library Loader extracts the relevant files from the archive and puts them in your KiCad libraries.  Assuming the information is there, it stores the symbol, the footprint and the 3d model.

Having used Ki-nTree a few times now, I have perhaps one feature request/suggestion.  When I look up and import a component, there is often but not always a suitable footprint already in the KiCad libraries.  Downloading footprints is something I try to do only when a suitable option is not available in the default KiCad libraries.  Worst case scenario, I have to build my own footprint from a spec sheet or from physically handling the component.  The KiCad footprint libraries are therefore really convenient and the program rightly protects them.  For those that I do download or build myself, I keep a personal footprint library in a cloud directory so I can access it on the go.  I'm sure there are others who have a personal footprint library stored separately from the system libraries.  Is there a simple way you could get Ki-nTree to be able to look in two directories for suitable footprints?  At the moment I have to abort the import, change the KiCad settings and start the import again in order to swap between the system footprint library and my personal footprint library.

Thanks!

**Comment by eeintech** [comment]
I guess you're right, selecting the KiCad **template** directory is not mentioned here: https://github.com/sparkmicro/Ki-nTree/#settings
So I will have to add it, thanks for the feedback.

Two separate footprint locations shouldn't be too much of an issue, it's a matter of adding a second path to the KiCad user settings window then instantiating the folders and files from two separate locations instead of one.
We can add it to the wishlist :smiley: Maybe you know enough python to post a PR? :wink:

**Comment by eeintech** [comment]
Or better yet, have an option for the user to select the KiCad symbol & footprints when running the selection step/window?

**Comment by Waranga-pa** [comment]
I'm not 100% shure if this error is related to this topic or connected to my lack of understandig data transfer from Ki-nTree to Kicad and honestly i don't see where problem lies. Error message looks like:

[MAIN]  Adding part to KiCad←[0m
[KCAD]  library_path: C:/Program Files/KiCad/share/kicad/library\Transistor_Array.lib
[KCAD]  Number of parts in library Transistor_Array.lib: 20
←[91m[INFO]     Error: Failed to add part to KiCad (incomplete InvenTree data)←[0m 

My path variables are:   
Symbol libraries path folder: C:\Program Files\KiCad\share\kicad\library\
Footprint libraries folder: C:\Program Files\KiCad\share\kicad\modules\
Symbol templates folder: C:\Users\user\AppData\Roaming\Python\Python39\site-packages\kintree\kicad\templates\

My kicad.yaml is untouched, not representing these changes set in GUI settings.
Please feel free to move this if you find it not connected to topic #68

Many thanks!

**Comment by eeintech** [comment]
@Waranga-pa Please open a new issue as this seems to be separate. In the new issue, can you please communicate the part number and supplier API (Digi-Key, Mouser) you have used? It seems related to the part information.

**Comment by cdwilson** [comment]
> Interesting... didn't think Python would ditch Tkinter, or could it be a brew driven decision?

FYI, Tkinter is not included in python from homebrew.  You need to install Tcl/Tk and Tkinter separately:
```
brew install tcl-tk
brew install python-tk
```

**Comment by eeintech** [comment]
Hello @rogers-jp 

Are you still interested into multiple paths for templates?

**Comment by eeintech** [comment]
No response from OP, closing.
